// Generated by scripts/licences.bash; do not edit by hand.

use super::{Group, Holder, Text};

// A copyright notice can outrun rustfmt, which then leaves the whole table as it
// finds it, so the table is written already laid out.
#[rustfmt::skip]
pub(super) const GROUPS: &[Group] = &[
    Group {
        licence: "Apache-2.0",
        text: include_str!("../../licences/Apache-2.0.txt"),
        holders: &[],
        unattributed: 27,
        variants: &[],
    },
    Group {
        licence: "BSD-2-Clause",
        text: include_str!("../../licences/BSD-2-Clause.txt"),
        holders: &[
            Holder {
                notice: "Copyright (c) 2015 David Roundy <roundyd@physics.oregonstate.edu>\nAll rights reserved.",
                crates: &[
                    "arrayref 0.3.9",
                ],
            },
        ],
        unattributed: 0,
        variants: &[],
    },
    Group {
        licence: "BSD-3-Clause",
        text: include_str!("../../licences/BSD-3-Clause.txt"),
        holders: &[
            Holder {
                notice: "Copyright (c) Radzivon Bartoshyk. All rights reserved.",
                crates: &[
                    "moxcms 0.8.1",
                    "pxfm 0.1.30",
                ],
            },
        ],
        unattributed: 0,
        variants: &[
            Text {
                crates: &[
                    "tiny-skia 0.11.4",
                    "tiny-skia-path 0.11.4",
                ],
                text: r#"Copyright (c) 2011 Google Inc. All rights reserved.
Copyright (c) 2020 Yevhenii Reizner All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

  * Redistributions of source code must retain the above copyright
    notice, this list of conditions and the following disclaimer.

  * Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in
    the documentation and/or other materials provided with the
    distribution.

  * Neither the name of the copyright holder nor the names of its
    contributors may be used to endorse or promote products derived
    from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"#,
            },
        ],
    },
    Group {
        licence: "ISC",
        text: include_str!("../../licences/ISC.txt"),
        holders: &[
            Holder {
                notice: "Copyright © 2015, Simonas Kazlauskas",
                crates: &[
                    "libloading 0.8.9",
                ],
            },
        ],
        unattributed: 0,
        variants: &[],
    },
    Group {
        licence: "MIT",
        text: include_str!("../../licences/MIT.txt"),
        holders: &[
            Holder {
                notice: "Copyright (c) 2012-2013 Mozilla Foundation",
                crates: &[
                    "cgl 0.3.2",
                    "core-foundation 0.9.4",
                    "core-foundation 0.10.1",
                    "core-foundation-sys 0.8.7",
                    "core-graphics 0.23.2",
                    "core-graphics-types 0.1.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2013-2014 The Rust Project Developers.\nCopyright (c) 2015-2020 The rust-hex Developers",
                crates: &[
                    "hex 0.4.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2013-2016 The rust-url developers",
                crates: &[
                    "form_urlencoded 1.2.2",
                ],
            },
            Holder {
                notice: "Copyright (c) 2013-2025 The rust-url developers",
                crates: &[
                    "data-url 0.3.2",
                    "idna 1.1.0",
                    "percent-encoding 2.3.2",
                    "url 2.5.8",
                ],
            },
            Holder {
                notice: "Copyright (c) 2014 Alex Crichton",
                crates: &[
                    "cfg-if 1.0.4",
                    "js-sys 0.3.98",
                    "scoped-tls 1.0.1",
                    "wasm-bindgen 0.2.121",
                    "wasm-bindgen-futures 0.4.71",
                    "wasm-bindgen-macro 0.2.121",
                    "wasm-bindgen-macro-support 0.2.121",
                    "wasm-bindgen-shared 0.2.121",
                    "web-sys 0.3.98",
                ],
            },
            Holder {
                notice: "Copyright (c) 2014 Chris Wong",
                crates: &[
                    "errno 0.3.14",
                ],
            },
            Holder {
                notice: "Copyright (c) 2014 John Slegers",
                crates: &[
                    "epaint_default_fonts 0.32.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2014 The Rust Project Developers",
                crates: &[
                    "bitflags 1.3.2",
                    "bitflags 2.13.1",
                    "log 0.4.33",
                    "num-bigint 0.4.8",
                    "num-integer 0.1.47",
                    "num-rational 0.4.2",
                    "num-traits 0.2.19",
                ],
            },
            Holder {
                notice: "Copyright (c) 2014 The Rust Project Developers\nCopyright (c) 2018 Ashley Mannix, Christopher Armstrong, Dylan DPC, Hunar Roop Kahlon",
                crates: &[
                    "uuid 1.24.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2014-2020 Optimal Computing (NZ) Ltd",
                crates: &[
                    "float-cmp 0.9.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2014-2026 Alex Crichton",
                crates: &[
                    "flate2 1.1.9",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015",
                crates: &[
                    "coreaudio-rs 0.14.2",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015 Alice Maz",
                crates: &[
                    "base64 0.22.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015 Elinor Berger",
                crates: &[
                    "wayland-backend 0.3.16",
                    "wayland-client 0.31.15",
                    "wayland-cursor 0.31.14",
                    "wayland-protocols 0.32.13",
                    "wayland-protocols-experimental 20250721.0.1",
                    "wayland-protocols-misc 0.3.12",
                    "wayland-protocols-plasma 0.3.12",
                    "wayland-protocols-wlr 0.3.12",
                    "wayland-scanner 0.31.11",
                    "wayland-sys 0.31.11",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015 Jonas Klesy",
                crates: &[
                    "coremidi-sys 3.2.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015 Patrick Reisert and the RtMidi contributors",
                crates: &[
                    "midir 0.11.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015 Steven Allen",
                crates: &[
                    "tempfile 3.27.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015 The Rust Project Developers",
                crates: &[
                    "unicode-segmentation 1.13.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015 The quick-error Developers",
                crates: &[
                    "quick-error 2.0.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015 Victor Berger",
                crates: &[
                    "dlib 0.5.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015 nwin",
                crates: &[
                    "png 0.17.16",
                    "png 0.18.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015-2018 The winapi-rs Developers",
                crates: &[
                    "winapi 0.3.9",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015-2021 David Henningsson, and other contributors.",
                crates: &[
                    "alsa 0.11.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2015-2022 Amod Malviya",
                crates: &[
                    "webbrowser 1.2.4",
                ],
            },
            Holder {
                notice: "Copyright (c) 2016 Alex Crichton\nCopyright (c) 2017 The Tokio Authors",
                crates: &[
                    "futures-channel 0.3.33",
                    "futures-core 0.3.33",
                    "futures-io 0.3.34",
                    "futures-macro 0.3.33",
                    "futures-task 0.3.33",
                    "futures-util 0.3.33",
                ],
            },
            Holder {
                notice: "Copyright (c) 2016 Amanieu d'Antras",
                crates: &[
                    "hashbrown 0.17.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2016 Christian Perez-Llamas",
                crates: &[
                    "coremidi 0.9.2",
                ],
            },
            Holder {
                notice: "Copyright (c) 2016 Johann Tuffe",
                crates: &[
                    "quick-xml 0.41.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2016 The Rust Project Developers",
                crates: &[
                    "lock_api 0.4.14",
                    "parking_lot 0.12.5",
                    "parking_lot_core 0.9.12",
                ],
            },
            Holder {
                notice: "Copyright (c) 2016--2017",
                crates: &[
                    "indexmap 2.14.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2016--2023",
                crates: &[
                    "equivalent 1.0.2",
                ],
            },
            Holder {
                notice: "Copyright (c) 2016-2019 Ulrik Sverdrup \"bluss\" and scopeguard developers",
                crates: &[
                    "scopeguard 1.2.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017 Gilad Naaman",
                crates: &[
                    "memoffset 0.9.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017 Maiddog",
                crates: &[
                    "imagesize 0.13.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017 Maik Klein",
                crates: &[
                    "enumflags2_derive 0.7.12",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017 Nikolai Vazquez",
                crates: &[
                    "static_assertions 1.1.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017 RON developers",
                crates: &[
                    "ron 0.10.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017 Robert Grosse",
                crates: &[
                    "stable_deref_trait 1.2.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017 The foreign-types Developers",
                crates: &[
                    "foreign-types 0.5.0",
                    "foreign-types-macros 0.2.4",
                    "foreign-types-shared 0.3.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017 tokio-jsonrpc developers",
                crates: &[
                    "signal-hook-registry 1.4.8",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017-2018 Junji Takakura",
                crates: &[
                    "io-kit-sys 0.4.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2017-2023 Maik Klein, Maja Kądziołka",
                crates: &[
                    "enumflags2 0.7.12",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 Lucas Timmins & Victor Berger",
                crates: &[
                    "smithay-clipboard 0.7.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 PistonDevelopers",
                crates: &[
                    "tiff 0.11.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 Raph Levien",
                crates: &[
                    "kurbo 0.11.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 Reizner Evgeniy",
                crates: &[
                    "simplecss 0.2.2",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 Sam Rijs, Alex Crichton and contributors",
                crates: &[
                    "crc32fast 1.5.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 The Servo Project Developers",
                crates: &[
                    "smallvec 1.15.2",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 Tom Kaitchuck",
                crates: &[
                    "ahash 0.8.12",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 Victor Berger",
                crates: &[
                    "calloop 0.13.0",
                    "calloop 0.14.4",
                    "smithay-client-toolkit 0.19.2",
                    "smithay-client-toolkit 0.20.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 Yevhenii Reizner",
                crates: &[
                    "roxmltree 0.20.0",
                    "svgtypes 0.15.3",
                    "ttf-parser 0.25.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018 diwic",
                crates: &[
                    "alsa-sys 0.4.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018-2025 The rust-random Project Developers\nCopyright (c) 2014 The Rust Project Developers",
                crates: &[
                    "getrandom 0.3.4",
                ],
            },
            Holder {
                notice: "Copyright (c) 2018-2026 The rust-random Project Developers\nCopyright (c) 2014 The Rust Project Developers",
                crates: &[
                    "getrandom 0.4.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2019 Carl Lerche",
                crates: &[
                    "slab 0.4.12",
                ],
            },
            Holder {
                notice: "Copyright (c) 2019 Kornel",
                crates: &[
                    "rgb 0.8.53",
                ],
            },
            Holder {
                notice: "Copyright (c) 2019 Nick Fitzgerald",
                crates: &[
                    "bumpalo 3.20.3",
                ],
            },
            Holder {
                notice: "Copyright (c) 2019 Nick Fitzgerald, 2021 Yuki Okushi",
                crates: &[
                    "mach2 0.4.3",
                    "mach2 0.5.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2019 Reizner Evgeniy",
                crates: &[
                    "xmlwriter 0.1.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2019 The Crossbeam Project Developers",
                crates: &[
                    "crossbeam-utils 0.8.22",
                ],
            },
            Holder {
                notice: "Copyright (c) 2019 The CryptoCorrosion Contributors",
                crates: &[
                    "ppv-lite86 0.2.21",
                ],
            },
            Holder {
                notice: "Copyright (c) 2019 Tokio Contributors",
                crates: &[
                    "tracing 0.1.44",
                    "tracing-attributes 0.1.31",
                    "tracing-core 0.1.36",
                ],
            },
            Holder {
                notice: "Copyright (c) 2019 Yevhenii Reizner",
                crates: &[
                    "pico-args 0.5.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2020 Ashish Myles and contributors",
                crates: &[
                    "downcast-rs 1.2.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2020 Bilal Elmoussaoui",
                crates: &[
                    "ashpd 0.11.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2020 Olivier Goffart <ogoffart@sixtyfps.io>",
                crates: &[
                    "document-features 0.2.12",
                ],
            },
            Holder {
                notice: "Copyright (c) 2020 Project Developers",
                crates: &[
                    "litrs 1.0.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2020 Samuele Esposito",
                crates: &[
                    "xcursor 0.3.11",
                ],
            },
            Holder {
                notice: "Copyright (c) 2020 Yevhenii Reizner\nCopyright (c) 2015 Dan Burkert",
                crates: &[
                    "memmap2 0.9.11",
                ],
            },
            Holder {
                notice: "Copyright (c) 2020 Yoshua Wuyts",
                crates: &[
                    "async-broadcast 0.7.2",
                ],
            },
            Holder {
                notice: "Copyright (c) 2020-2021 Joshua Barretto",
                crates: &[
                    "pollster 0.4.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2022 Bartłomiej Maryńczak",
                crates: &[
                    "rfd 0.15.4",
                ],
            },
            Holder {
                notice: "Copyright (c) 2022 The Arboard contributors",
                crates: &[
                    "arboard 3.6.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2022 Yevhenii Reizner",
                crates: &[
                    "strict-num 0.1.1",
                ],
            },
            Holder {
                notice: "Copyright (c) 2023 Kirill Chibisov",
                crates: &[
                    "calloop-wayland-source 0.3.0",
                    "calloop-wayland-source 0.4.1",
                    "wayland-csd-frame 0.3.0",
                    "xkbcommon-dl 0.4.2",
                ],
            },
            Holder {
                notice: "Copyright (c) 2023 dAxpeDDa",
                crates: &[
                    "web-time 1.1.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2024 Zeeshan Ali Khan & zbus contributors",
                crates: &[
                    "zbus 5.19.0",
                    "zbus_macros 5.19.0",
                    "zbus_names 4.3.4",
                    "zvariant 5.14.0",
                    "zvariant_derive 5.14.0",
                ],
            },
            Holder {
                notice: "Copyright (c) 2026 Zeeshan Ali Khan & zcheapstr contributors",
                crates: &[
                    "zcheapstr 1.1.0",
                ],
            },
            Holder {
                notice: "Copyright (c) HeroicKatora 2020",
                crates: &[
                    "weezl 0.1.12",
                ],
            },
            Holder {
                notice: "Copyright (c) Individual contributors",
                crates: &[
                    "toml_datetime 1.1.1+spec-1.1.0",
                    "toml_edit 0.25.13+spec-1.1.0",
                    "toml_parser 1.1.3+spec-1.1.0",
                ],
            },
            Holder {
                notice: "Copyright (c) Microsoft Corporation.",
                crates: &[
                    "windows 0.62.2",
                    "windows-collections 0.3.2",
                    "windows-core 0.62.2",
                    "windows-future 0.3.2",
                    "windows-implement 0.60.2",
                    "windows-interface 0.59.3",
                    "windows-link 0.2.1",
                    "windows-numerics 0.3.1",
                    "windows-result 0.4.1",
                    "windows-strings 0.5.1",
                    "windows-sys 0.48.0",
                    "windows-sys 0.52.0",
                    "windows-sys 0.59.0",
                    "windows-sys 0.61.2",
                    "windows-targets 0.48.5",
                    "windows-targets 0.52.6",
                    "windows-threading 0.2.1",
                    "windows_x86_64_gnu 0.48.5",
                    "windows_x86_64_gnu 0.52.6",
                ],
            },
            Holder {
                notice: "Copyright (c) Microsoft Corporation. All rights reserved.",
                crates: &[
                    "uds_windows 1.2.1",
                ],
            },
            Holder {
                notice: "Copyright (c) Steven Sheldon",
                crates: &[
                    "block2 0.5.1",
                    "block2 0.6.2",
                    "dispatch 0.2.0",
                    "objc-sys 0.3.5",
                    "objc2 0.5.2",
                    "objc2 0.6.4",
                    "objc2-app-kit 0.2.2",
                    "objc2-encode 4.1.0",
                    "objc2-foundation 0.2.2",
                    "objc2-foundation 0.3.2",
                ],
            },
            Holder {
                notice: "Copyright (c) The Rodio Project Contributors",
                crates: &[
                    "rodio 0.22.2",
                ],
            },
            Holder {
                notice: "Copyright (c) The Rust Project Developers",
                crates: &[
                    "libc 0.2.189",
                ],
            },
            Holder {
                notice: "Copyright (c) The rust-url developers",
                crates: &[
                    "idna_adapter 1.2.2",
                ],
            },
            Holder {
                notice: "Copyright (c) Ulrik Sverdrup \"bluss\" 2015-2023",
                crates: &[
                    "arrayvec 0.7.8",
                ],
            },
            Holder {
                notice: "Copyright (c) [2021] [Marvin Countryman]",
                crates: &[
                    "simd-adler32 0.3.10",
                ],
            },
            Holder {
                notice: "Copyright 2016 Nika Layzell",
                crates: &[
                    "synstructure 0.13.2",
                ],
            },
            Holder {
                notice: "Copyright 2017 the Resvg Authors",
                crates: &[
                    "resvg 0.45.1",
                    "usvg 0.45.1",
                ],
            },
            Holder {
                notice: "Copyright 2018 Developers of the Rand project\nCopyright (c) 2014 The Rust Project Developers",
                crates: &[
                    "rand 0.9.5",
                    "rand_chacha 0.9.0",
                    "rand_core 0.9.5",
                ],
            },
            Holder {
                notice: "Copyright 2018 Parity Technologies (UK) Ltd.",
                crates: &[
                    "nohash-hasher 0.2.0",
                ],
            },
            Holder {
                notice: "Copyright 2019 as-raw-xcb-connection Contributers",
                crates: &[
                    "as-raw-xcb-connection 1.0.1",
                ],
            },
            Holder {
                notice: "Copyright 2019 x11rb Contributers",
                crates: &[
                    "x11rb 0.13.2",
                    "x11rb-protocol 0.13.2",
                ],
            },
            Holder {
                notice: "Copyright 2023 The Fuchsia Authors",
                crates: &[
                    "zerocopy 0.8.56",
                    "zerocopy-derive 0.8.56",
                ],
            },
            Holder {
                notice: "Copyright Mozilla Foundation",
                crates: &[
                    "utf8_iter 1.0.4",
                ],
            },
            Holder {
                notice: "Copyright © 2021 The pdf-rs contributers.",
                crates: &[
                    "fax 0.2.7",
                ],
            },
            Holder {
                notice: "Copyright © 2022 Kirill Chibisov",
                crates: &[
                    "glutin-winit 0.5.0",
                ],
            },
            Holder {
                notice: "© 2016 Bertram Truong\n© 2021 Kornel Lesiński",
                crates: &[
                    "urlencoding 2.1.3",
                ],
            },
        ],
        unattributed: 55,
        variants: &[
            Text {
                crates: &[
                    "dpi 0.1.2",
                ],
                text: r#"rust-lang/libm as a whole is available for use under the MIT license:

------------------------------------------------------------------------------
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
------------------------------------------------------------------------------

This Rust library contains the following copyrights:

    Copyright (c) 2018 Jorge Aparicio

Portions of this software are derived from third-party works licensed under
terms compatible with the above MIT license:

* musl libc https://www.musl-libc.org/. This library contains the following
  copyright:

      Copyright © 2005-2020 Rich Felker, et al.

* The CORE-MATH project https://core-math.gitlabpages.inria.fr/. CORE-MATH
  routines are available under the MIT license on a per-file basis.

The musl libc COPYRIGHT file also includes the following notice relevant to
math portions of the library:

------------------------------------------------------------------------------
Much of the math library code (src/math/* and src/complex/*) is
Copyright © 1993,2004 Sun Microsystems or
Copyright © 2003-2011 David Schultz or
Copyright © 2003-2009 Steven G. Kargl or
Copyright © 2003-2009 Bruce D. Evans or
Copyright © 2008 Stephen L. Moshier or
Copyright © 2017-2018 Arm Limited
and labelled as such in comments in the individual source files. All
have been licensed under extremely permissive terms.
------------------------------------------------------------------------------
"#,
            },
            Text {
                crates: &[
                    "zip 2.4.2",
                ],
                text: r#"The MIT License (MIT)

Copyright (c) 2014 Mathijs van de Nes

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

Some files in the "tests/data" subdirectory of this repository are under other
licences; see files named LICENSE.*.txt for details."#,
            },
        ],
    },
    Group {
        licence: "Unicode-3.0",
        text: include_str!("../../licences/Unicode-3.0.txt"),
        holders: &[
            Holder {
                notice: "Copyright © 1991-2023 Unicode, Inc.",
                crates: &[
                    "unicode-ident 1.0.24",
                ],
            },
        ],
        unattributed: 0,
        variants: &[
            Text {
                crates: &[
                    "icu_collections 2.2.0",
                    "icu_locale_core 2.2.0",
                    "icu_normalizer 2.2.0",
                    "icu_normalizer_data 2.2.0",
                    "icu_properties 2.2.0",
                    "icu_properties_data 2.2.0",
                    "icu_provider 2.2.0",
                    "litemap 0.8.2",
                    "potential_utf 0.1.5",
                    "tinystr 0.8.3",
                    "writeable 0.6.3",
                    "yoke 0.8.3",
                    "yoke-derive 0.8.2",
                    "zerofrom 0.1.8",
                    "zerofrom-derive 0.1.7",
                    "zerotrie 0.2.4",
                    "zerovec 0.11.6",
                    "zerovec-derive 0.11.3",
                ],
                text: r#"UNICODE LICENSE V3

COPYRIGHT AND PERMISSION NOTICE

Copyright © 2020-2024 Unicode, Inc.

NOTICE TO USER: Carefully read the following legal agreement. BY
DOWNLOADING, INSTALLING, COPYING OR OTHERWISE USING DATA FILES, AND/OR
SOFTWARE, YOU UNEQUIVOCALLY ACCEPT, AND AGREE TO BE BOUND BY, ALL OF THE
TERMS AND CONDITIONS OF THIS AGREEMENT. IF YOU DO NOT AGREE, DO NOT
DOWNLOAD, INSTALL, COPY, DISTRIBUTE OR USE THE DATA FILES OR SOFTWARE.

Permission is hereby granted, free of charge, to any person obtaining a
copy of data files and any associated documentation (the "Data Files") or
software and any associated documentation (the "Software") to deal in the
Data Files or Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, and/or sell
copies of the Data Files or Software, and to permit persons to whom the
Data Files or Software are furnished to do so, provided that either (a)
this copyright and permission notice appear with all copies of the Data
Files or Software, or (b) this copyright and permission notice appear in
associated Documentation.

THE DATA FILES AND SOFTWARE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY
KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT OF
THIRD PARTY RIGHTS.

IN NO EVENT SHALL THE COPYRIGHT HOLDER OR HOLDERS INCLUDED IN THIS NOTICE
BE LIABLE FOR ANY CLAIM, OR ANY SPECIAL INDIRECT OR CONSEQUENTIAL DAMAGES,
OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS,
WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THE DATA
FILES OR SOFTWARE.

Except as contained in this notice, the name of a copyright holder shall
not be used in advertising or otherwise to promote the sale, use or other
dealings in these Data Files or Software without prior written
authorization of the copyright holder.

SPDX-License-Identifier: Unicode-3.0

—

Portions of ICU4X may have been adapted from ICU4C and/or ICU4J.
ICU 1.8.1 to ICU 57.1 © 1995-2016 International Business Machines Corporation and others.
"#,
            },
        ],
    },
];

#[cfg(test)]
pub(super) const LOCKED: &[(&str, &str)] = &[
    ("ab_glyph", "0.2.32"),
    ("ab_glyph_rasterizer", "0.1.10"),
    ("accesskit", "0.19.0"),
    ("adler2", "2.0.1"),
    ("ahash", "0.8.12"),
    ("alsa", "0.11.0"),
    ("alsa-sys", "0.4.0"),
    ("android-activity", "0.6.1"),
    ("android-build", "0.1.4"),
    ("android-properties", "0.2.2"),
    ("anstream", "1.0.0"),
    ("anstyle", "1.0.14"),
    ("anstyle-parse", "1.0.0"),
    ("anstyle-query", "1.1.5"),
    ("anstyle-wincon", "3.0.11"),
    ("arbitrary", "1.4.2"),
    ("arboard", "3.6.1"),
    ("arrayref", "0.3.9"),
    ("arrayvec", "0.7.8"),
    ("as-raw-xcb-connection", "1.0.1"),
    ("ashpd", "0.11.1"),
    ("async-broadcast", "0.7.2"),
    ("async-channel", "2.5.0"),
    ("async-executor", "1.14.0"),
    ("async-fs", "2.2.0"),
    ("async-io", "2.6.0"),
    ("async-lock", "3.4.2"),
    ("async-net", "2.0.0"),
    ("async-process", "2.5.0"),
    ("async-recursion", "1.1.1"),
    ("async-signal", "0.2.14"),
    ("async-task", "4.7.1"),
    ("async-trait", "0.1.92"),
    ("atomic-waker", "1.1.2"),
    ("autocfg", "1.5.1"),
    ("base64", "0.22.1"),
    ("bit-set", "0.8.0"),
    ("bit-vec", "0.8.0"),
    ("bitflags", "1.3.2"),
    ("bitflags", "2.13.1"),
    ("block2", "0.5.1"),
    ("block2", "0.6.2"),
    ("blocking", "1.6.2"),
    ("bumpalo", "3.20.3"),
    ("bytemuck", "1.25.2"),
    ("bytemuck_derive", "1.12.0"),
    ("byteorder-lite", "0.1.0"),
    ("bytes", "1.12.1"),
    ("calloop", "0.13.0"),
    ("calloop", "0.14.4"),
    ("calloop-wayland-source", "0.3.0"),
    ("calloop-wayland-source", "0.4.1"),
    ("cc", "1.4.2"),
    ("cesu8", "1.1.0"),
    ("cfg-if", "1.0.4"),
    ("cfg_aliases", "0.2.2"),
    ("cgl", "0.3.2"),
    ("clap", "4.6.6"),
    ("clap_builder", "4.6.6"),
    ("clap_derive", "4.6.4"),
    ("clap_lex", "1.1.0"),
    ("clipboard-win", "5.4.1"),
    ("codespan-reporting", "0.12.0"),
    ("colorchoice", "1.0.5"),
    ("combine", "4.6.7"),
    ("concurrent-queue", "2.5.0"),
    ("console", "0.16.4"),
    ("core-foundation", "0.9.4"),
    ("core-foundation", "0.10.1"),
    ("core-foundation-sys", "0.8.7"),
    ("core-graphics", "0.23.2"),
    ("core-graphics-types", "0.1.3"),
    ("coreaudio-rs", "0.14.2"),
    ("coremidi", "0.9.2"),
    ("coremidi-sys", "3.2.1"),
    ("cpal", "0.17.3"),
    ("crc32fast", "1.5.0"),
    ("crcxx", "0.3.1"),
    ("crossbeam-utils", "0.8.22"),
    ("crunchy", "0.2.4"),
    ("cursor-icon", "1.2.0"),
    ("dasp_sample", "0.11.0"),
    ("data-url", "0.3.2"),
    ("derive_arbitrary", "1.4.2"),
    ("dialoguer", "0.12.0"),
    ("dispatch", "0.2.0"),
    ("dispatch2", "0.3.1"),
    ("displaydoc", "0.2.7"),
    ("dlib", "0.5.3"),
    ("dlopen2", "0.9.0"),
    ("document-features", "0.2.12"),
    ("downcast-rs", "1.2.1"),
    ("dpi", "0.1.2"),
    ("ecolor", "0.32.3"),
    ("eframe", "0.32.3"),
    ("egui", "0.32.3"),
    ("egui-wgpu", "0.32.3"),
    ("egui-winit", "0.32.3"),
    ("egui_extras", "0.32.3"),
    ("egui_glow", "0.32.3"),
    ("emath", "0.32.3"),
    ("encode_unicode", "1.0.0"),
    ("endi", "1.1.1"),
    ("enum-map", "2.7.3"),
    ("enum-map-derive", "0.17.0"),
    ("enumflags2", "0.7.12"),
    ("enumflags2_derive", "0.7.12"),
    ("enumn", "0.1.14"),
    ("epaint", "0.32.3"),
    ("epaint_default_fonts", "0.32.3"),
    ("equivalent", "1.0.2"),
    ("errno", "0.3.14"),
    ("error-code", "3.3.2"),
    ("escape8259", "0.5.3"),
    ("euclid", "0.22.14"),
    ("event-listener", "5.4.2"),
    ("event-listener-strategy", "0.5.4"),
    ("fastrand", "2.5.0"),
    ("fax", "0.2.7"),
    ("fdeflate", "0.3.7"),
    ("find-msvc-tools", "0.1.10"),
    ("flate2", "1.1.9"),
    ("float-cmp", "0.9.0"),
    ("foldhash", "0.1.5"),
    ("foreign-types", "0.5.0"),
    ("foreign-types-macros", "0.2.4"),
    ("foreign-types-shared", "0.3.1"),
    ("form_urlencoded", "1.2.2"),
    ("futures-channel", "0.3.33"),
    ("futures-core", "0.3.33"),
    ("futures-io", "0.3.34"),
    ("futures-lite", "2.6.1"),
    ("futures-macro", "0.3.33"),
    ("futures-task", "0.3.33"),
    ("futures-util", "0.3.33"),
    ("gethostname", "1.1.0"),
    ("getrandom", "0.3.4"),
    ("getrandom", "0.4.3"),
    ("gl_generator", "0.14.0"),
    ("glob", "0.3.4"),
    ("glow", "0.16.0"),
    ("glutin", "0.32.3"),
    ("glutin-winit", "0.5.0"),
    ("glutin_egl_sys", "0.7.1"),
    ("glutin_glx_sys", "0.6.1"),
    ("glutin_wgl_sys", "0.6.1"),
    ("half", "2.7.1"),
    ("hashbrown", "0.15.5"),
    ("hashbrown", "0.17.1"),
    ("heck", "0.5.0"),
    ("hermit-abi", "0.5.2"),
    ("hex", "0.4.3"),
    ("hexf-parse", "0.2.1"),
    ("home", "0.5.12"),
    ("icu_collections", "2.2.0"),
    ("icu_locale_core", "2.2.0"),
    ("icu_normalizer", "2.2.0"),
    ("icu_normalizer_data", "2.2.0"),
    ("icu_properties", "2.2.0"),
    ("icu_properties_data", "2.2.0"),
    ("icu_provider", "2.2.0"),
    ("idna", "1.1.0"),
    ("idna_adapter", "1.2.2"),
    ("image", "0.25.10"),
    ("imagesize", "0.13.0"),
    ("indexmap", "2.14.0"),
    ("io-kit-sys", "0.4.1"),
    ("is_terminal_polyfill", "1.70.2"),
    ("itoa", "1.0.18"),
    ("java-locator", "0.1.9"),
    ("jni", "0.21.1"),
    ("jni", "0.22.4"),
    ("jni-macros", "0.22.4"),
    ("jni-min-helper", "0.3.4"),
    ("jni-sys", "0.3.1"),
    ("jni-sys", "0.4.1"),
    ("jni-sys-macros", "0.4.1"),
    ("jobserver", "0.1.35"),
    ("js-sys", "0.3.98"),
    ("khronos_api", "3.1.0"),
    ("kurbo", "0.11.3"),
    ("libc", "0.2.189"),
    ("libloading", "0.7.4"),
    ("libloading", "0.8.9"),
    ("libm", "0.2.16"),
    ("libredox", "0.1.19"),
    ("libtest-mimic", "0.8.2"),
    ("linux-raw-sys", "0.4.15"),
    ("linux-raw-sys", "0.12.1"),
    ("litemap", "0.8.2"),
    ("litrs", "1.0.0"),
    ("lock_api", "0.4.14"),
    ("log", "0.4.33"),
    ("mach2", "0.4.3"),
    ("mach2", "0.5.0"),
    ("memchr", "2.8.3"),
    ("memmap2", "0.9.11"),
    ("memoffset", "0.9.1"),
    ("midir", "0.11.0"),
    ("miniz_oxide", "0.8.9"),
    ("moxcms", "0.8.1"),
    ("naga", "25.0.1"),
    ("ndk", "0.9.0"),
    ("ndk-context", "0.1.1"),
    ("ndk-sys", "0.6.0+11769913"),
    ("nohash-hasher", "0.2.0"),
    ("num-bigint", "0.4.8"),
    ("num-derive", "0.4.2"),
    ("num-integer", "0.1.47"),
    ("num-rational", "0.4.2"),
    ("num-traits", "0.2.19"),
    ("num_enum", "0.7.6"),
    ("num_enum_derive", "0.7.6"),
    ("nusb", "0.1.14"),
    ("objc-sys", "0.3.5"),
    ("objc2", "0.5.2"),
    ("objc2", "0.6.4"),
    ("objc2-app-kit", "0.2.2"),
    ("objc2-app-kit", "0.3.2"),
    ("objc2-audio-toolbox", "0.3.2"),
    ("objc2-avf-audio", "0.3.2"),
    ("objc2-cloud-kit", "0.2.2"),
    ("objc2-contacts", "0.2.2"),
    ("objc2-core-audio", "0.3.2"),
    ("objc2-core-audio-types", "0.3.2"),
    ("objc2-core-data", "0.2.2"),
    ("objc2-core-foundation", "0.3.2"),
    ("objc2-core-graphics", "0.3.2"),
    ("objc2-core-image", "0.2.2"),
    ("objc2-core-location", "0.2.2"),
    ("objc2-encode", "4.1.0"),
    ("objc2-foundation", "0.2.2"),
    ("objc2-foundation", "0.3.2"),
    ("objc2-io-surface", "0.3.2"),
    ("objc2-link-presentation", "0.2.2"),
    ("objc2-metal", "0.2.2"),
    ("objc2-quartz-core", "0.2.2"),
    ("objc2-symbols", "0.2.2"),
    ("objc2-ui-kit", "0.2.2"),
    ("objc2-uniform-type-identifiers", "0.2.2"),
    ("objc2-user-notifications", "0.2.2"),
    ("once_cell", "1.21.4"),
    ("once_cell_polyfill", "1.70.2"),
    ("orbclient", "0.3.55"),
    ("ordered-stream", "0.2.0"),
    ("owned_ttf_parser", "0.25.1"),
    ("parking", "2.2.1"),
    ("parking_lot", "0.12.5"),
    ("parking_lot_core", "0.9.12"),
    ("percent-encoding", "2.3.2"),
    ("pico-args", "0.5.0"),
    ("pin-project", "1.1.13"),
    ("pin-project-internal", "1.1.13"),
    ("pin-project-lite", "0.2.17"),
    ("piper", "0.2.5"),
    ("pkg-config", "0.3.33"),
    ("plain", "0.2.3"),
    ("png", "0.17.16"),
    ("png", "0.18.1"),
    ("polling", "3.11.0"),
    ("pollster", "0.4.0"),
    ("portable-atomic", "1.15.0"),
    ("potential_utf", "0.1.5"),
    ("ppv-lite86", "0.2.21"),
    ("proc-macro-crate", "3.5.0"),
    ("proc-macro2", "1.0.107"),
    ("process_path", "0.1.4"),
    ("profiling", "1.0.18"),
    ("pxfm", "0.1.30"),
    ("quick-error", "2.0.1"),
    ("quick-xml", "0.41.0"),
    ("quote", "1.0.47"),
    ("r-efi", "5.3.0"),
    ("r-efi", "6.0.0"),
    ("rand", "0.9.5"),
    ("rand_chacha", "0.9.0"),
    ("rand_core", "0.9.5"),
    ("raw-window-handle", "0.6.2"),
    ("redox_syscall", "0.4.1"),
    ("redox_syscall", "0.5.18"),
    ("redox_syscall", "0.9.2"),
    ("renderdoc-sys", "1.1.0"),
    ("resvg", "0.45.1"),
    ("rfd", "0.15.4"),
    ("rgb", "0.8.53"),
    ("rodio", "0.22.2"),
    ("ron", "0.10.1"),
    ("roxmltree", "0.20.0"),
    ("rustc-hash", "1.1.0"),
    ("rustc-hash", "2.1.3"),
    ("rustc_version", "0.4.1"),
    ("rustix", "0.38.44"),
    ("rustix", "1.1.4"),
    ("rustversion", "1.0.23"),
    ("same-file", "1.0.6"),
    ("scoped-tls", "1.0.1"),
    ("scopeguard", "1.2.0"),
    ("semver", "1.0.28"),
    ("serde", "1.0.229"),
    ("serde_core", "1.0.229"),
    ("serde_derive", "1.0.229"),
    ("serde_json", "1.0.151"),
    ("serde_repr", "0.1.21"),
    ("shell-words", "1.1.1"),
    ("shlex", "2.0.1"),
    ("signal-hook-registry", "1.4.8"),
    ("simd-adler32", "0.3.10"),
    ("simd_cesu8", "1.2.0"),
    ("simdutf8", "0.1.5"),
    ("simplecss", "0.2.2"),
    ("siphasher", "1.0.3"),
    ("slab", "0.4.12"),
    ("slotmap", "1.1.1"),
    ("smallvec", "1.15.2"),
    ("smithay-client-toolkit", "0.19.2"),
    ("smithay-client-toolkit", "0.20.0"),
    ("smithay-clipboard", "0.7.3"),
    ("smol_str", "0.2.2"),
    ("stable_deref_trait", "1.2.1"),
    ("static_assertions", "1.1.0"),
    ("strict-num", "0.1.1"),
    ("strsim", "0.11.1"),
    ("strum", "0.26.3"),
    ("strum_macros", "0.26.4"),
    ("svgtypes", "0.15.3"),
    ("syn", "2.0.119"),
    ("syn", "3.0.3"),
    ("synstructure", "0.13.2"),
    ("tempfile", "3.27.0"),
    ("termcolor", "1.4.1"),
    ("thiserror", "1.0.69"),
    ("thiserror", "2.0.20"),
    ("thiserror-impl", "1.0.69"),
    ("thiserror-impl", "2.0.20"),
    ("tiff", "0.11.3"),
    ("tiny-skia", "0.11.4"),
    ("tiny-skia-path", "0.11.4"),
    ("tinystr", "0.8.3"),
    ("toml_datetime", "1.1.1+spec-1.1.0"),
    ("toml_edit", "0.25.13+spec-1.1.0"),
    ("toml_parser", "1.1.3+spec-1.1.0"),
    ("tracing", "0.1.44"),
    ("tracing-attributes", "0.1.31"),
    ("tracing-core", "0.1.36"),
    ("ttf-parser", "0.25.1"),
    ("type-map", "0.5.1"),
    ("uds_windows", "1.2.1"),
    ("unicode-ident", "1.0.24"),
    ("unicode-segmentation", "1.13.3"),
    ("unicode-width", "0.2.2"),
    ("url", "2.5.8"),
    ("urlencoding", "2.1.3"),
    ("usvg", "0.45.1"),
    ("utf8_iter", "1.0.4"),
    ("utf8parse", "0.2.2"),
    ("uuid", "1.24.0"),
    ("version_check", "0.9.5"),
    ("walkdir", "2.5.0"),
    ("wasip2", "1.0.4+wasi-0.2.12"),
    ("wasm-bindgen", "0.2.121"),
    ("wasm-bindgen-futures", "0.4.71"),
    ("wasm-bindgen-macro", "0.2.121"),
    ("wasm-bindgen-macro-support", "0.2.121"),
    ("wasm-bindgen-shared", "0.2.121"),
    ("wayland-backend", "0.3.16"),
    ("wayland-client", "0.31.15"),
    ("wayland-csd-frame", "0.3.0"),
    ("wayland-cursor", "0.31.14"),
    ("wayland-protocols", "0.32.13"),
    ("wayland-protocols-experimental", "20250721.0.1"),
    ("wayland-protocols-misc", "0.3.12"),
    ("wayland-protocols-plasma", "0.3.12"),
    ("wayland-protocols-wlr", "0.3.12"),
    ("wayland-scanner", "0.31.11"),
    ("wayland-sys", "0.31.11"),
    ("web-sys", "0.3.98"),
    ("web-time", "1.1.0"),
    ("webbrowser", "1.2.4"),
    ("weezl", "0.1.12"),
    ("wgpu", "25.0.2"),
    ("wgpu-core", "25.0.2"),
    ("wgpu-core-deps-windows-linux-android", "25.0.0"),
    ("wgpu-hal", "25.0.2"),
    ("wgpu-types", "25.0.0"),
    ("winapi", "0.3.9"),
    ("winapi-i686-pc-windows-gnu", "0.4.0"),
    ("winapi-util", "0.1.11"),
    ("winapi-x86_64-pc-windows-gnu", "0.4.0"),
    ("windows", "0.62.2"),
    ("windows-collections", "0.3.2"),
    ("windows-core", "0.62.2"),
    ("windows-future", "0.3.2"),
    ("windows-implement", "0.60.2"),
    ("windows-interface", "0.59.3"),
    ("windows-link", "0.2.1"),
    ("windows-numerics", "0.3.1"),
    ("windows-result", "0.4.1"),
    ("windows-strings", "0.5.1"),
    ("windows-sys", "0.45.0"),
    ("windows-sys", "0.48.0"),
    ("windows-sys", "0.52.0"),
    ("windows-sys", "0.59.0"),
    ("windows-sys", "0.61.2"),
    ("windows-targets", "0.42.2"),
    ("windows-targets", "0.48.5"),
    ("windows-targets", "0.52.6"),
    ("windows-threading", "0.2.1"),
    ("windows_aarch64_gnullvm", "0.42.2"),
    ("windows_aarch64_gnullvm", "0.48.5"),
    ("windows_aarch64_gnullvm", "0.52.6"),
    ("windows_aarch64_msvc", "0.42.2"),
    ("windows_aarch64_msvc", "0.48.5"),
    ("windows_aarch64_msvc", "0.52.6"),
    ("windows_i686_gnu", "0.42.2"),
    ("windows_i686_gnu", "0.48.5"),
    ("windows_i686_gnu", "0.52.6"),
    ("windows_i686_gnullvm", "0.52.6"),
    ("windows_i686_msvc", "0.42.2"),
    ("windows_i686_msvc", "0.48.5"),
    ("windows_i686_msvc", "0.52.6"),
    ("windows_x86_64_gnu", "0.42.2"),
    ("windows_x86_64_gnu", "0.48.5"),
    ("windows_x86_64_gnu", "0.52.6"),
    ("windows_x86_64_gnullvm", "0.42.2"),
    ("windows_x86_64_gnullvm", "0.48.5"),
    ("windows_x86_64_gnullvm", "0.52.6"),
    ("windows_x86_64_msvc", "0.42.2"),
    ("windows_x86_64_msvc", "0.48.5"),
    ("windows_x86_64_msvc", "0.52.6"),
    ("winit", "0.30.13"),
    ("winnow", "1.0.4"),
    ("wit-bindgen", "0.57.1"),
    ("writeable", "0.6.3"),
    ("x11-dl", "2.21.0"),
    ("x11rb", "0.13.2"),
    ("x11rb-protocol", "0.13.2"),
    ("xcursor", "0.3.11"),
    ("xkbcommon-dl", "0.4.2"),
    ("xkeysym", "0.2.1"),
    ("xml-rs", "0.8.29"),
    ("xmlwriter", "0.1.0"),
    ("yoke", "0.8.3"),
    ("yoke-derive", "0.8.2"),
    ("zbus", "5.19.0"),
    ("zbus_macros", "5.19.0"),
    ("zbus_names", "4.3.4"),
    ("zcheapstr", "1.1.0"),
    ("zerocopy", "0.8.56"),
    ("zerocopy-derive", "0.8.56"),
    ("zerofrom", "0.1.8"),
    ("zerofrom-derive", "0.1.7"),
    ("zerotrie", "0.2.4"),
    ("zerovec", "0.11.6"),
    ("zerovec-derive", "0.11.3"),
    ("zip", "2.4.2"),
    ("zmij", "1.0.23"),
    ("zopfli", "0.8.3"),
    ("zune-core", "0.5.3"),
    ("zune-jpeg", "0.5.15"),
    ("zvariant", "5.14.0"),
    ("zvariant_derive", "5.14.0"),
    ("zvariant_utils", "4.0.0"),
];
