[package]
name = "libnord-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libnord = { version = "0.1.0", path = "../libnord" }
crcxx = "0.3.1"

[[bin]]
name = "nord-util"
path = "src/main.rs"

[[bin]]
name = "findcrc"
path = "src/findcrc.rs"
