#!/usr/bin/env bash
# nix-deps: cargo cargo-about git jq nix
# Regenerate the licence notices drawbar's About box shows for the Rust crates in it.
set -euo pipefail

repo="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
drawbar="$repo/crates/drawbar"
licences="$drawbar/licences"
out="$drawbar/src/about/crates.rs"

about="$(cargo about generate --format json --fail --locked \
  --manifest-path "$drawbar/Cargo.toml" --config "$drawbar/about.toml")"

# licences.tsv supplies the text of a crate whose package carries none, fetched from
# the upstream file its `source` column names.
vendored="$(tail -n +2 "$repo/scripts/licences.tsv" |
  while IFS=$'\t' read -r name version licence file _; do
    jq -n --arg crate "$name $version" --arg licence "$licence" \
      --rawfile text "$licences/$file" '{$crate, $licence, $text}'
  done | jq -s 'INDEX(.crate)')"

# Apache-2.0.txt is https://www.apache.org/licenses/LICENSE-2.0.txt verbatim.
entries="$(jq --argjson vendored "$vendored" --rawfile apache "$licences/Apache-2.0.txt" '
  # Licences that ask nothing of a binary copy.
  def unconditional: [
    "0BSD",      # grants use "for any purpose with or without fee" and sets no condition
    "BSL-1.0",   # its notice may be left out of "machine-executable object code"
    "CC0-1.0",   # section 2 waives copyright and related rights outright
    "Unlicense", # dedicates the work to the public domain
    "Zlib"       # clause 1: acknowledgment "is not required"; clause 3 binds source only
  ];
  # The hand-written font rows of the About box carry these for epaint_default_fonts.
  def fonts: ["OFL-1.1", "Ubuntu-font-1.0"];
  # The SPDX template of a notice, whose copyright line names no one.
  def unfilled: ascii_downcase | test("<year>|<owner>|<copyright holder");
  def offers_apache: [splits("\\s+OR\\s+|/") | gsub("^[(\\s]+|[)\\s]+$"; "")] | index("Apache-2.0");

  [
    .licenses[] as $licence
    | $licence.used_by[].crate
    # Path crates are the workspace, which the drawbar row covers.
    | select(.source != null)
    | select($licence.id | IN(unconditional[]) | not)
    | select(.name != "epaint_default_fonts" or ($licence.id | IN(fonts[]) | not))
    | {
        crate: "\(.name) \(.version)",
        name,
        version,
        offers_apache: (.license // "" | offers_apache != null),
        dir: (.manifest_path | rtrimstr("/Cargo.toml")),
        licence: $licence.id,
        text: $licence.text
      }
  ]
  | (map(.crate) | unique) as $shipped
  | ($vendored | keys - $shipped) as $stale
  | if $stale != [] then error("licences.tsv names crates drawbar does not ship: \($stale)") end
  | map(
      if $vendored[.crate] == null then .
      elif $vendored[.crate].licence == .licence then .text = $vendored[.crate].text
      else error("\(.crate) is under \(.licence), not the \($vendored[.crate].licence) licences.tsv gives")
      end
    )
  # Apache-2.0 needs no copyright line, so its text is complete where the other licence
  # a crate offers is only a template.
  | map(if (.text | unfilled) and .offers_apache then .licence = "Apache-2.0" | .text = $apache end)
  # rustc reads CRLF in a raw string as LF, and rejects a lone CR.
  | map(.text |= gsub("\r\n"; "\n"))
  | (map(select(.text | unfilled) | .crate) | unique) as $unfilled
  | if $unfilled != [] then error("these crates have only a licence template: \($unfilled)") end
  | if any(.[].text; test("\r|\"#")) then error("a licence text holds a CR or \"#") end
' <<<"$about")"

# Apache-2.0 §4(d) requires a NOTICE file's contents to travel with the binary.
notices="$(jq -r '.[] | select(.licence == "Apache-2.0") | .dir' <<<"$entries" | sort -u |
  xargs -I{} find {} -maxdepth 1 -iname 'NOTICE*')"
if [[ -n $notices ]]; then
  printf 'the About box does not carry these NOTICE files:\n%s\n' "$notices" >&2
  exit 1
fi

locked="$(awk -F' = ' '
  $0 == "[[package]]" { name = version = "" }
  $1 == "name" { name = $2 }
  $1 == "version" { version = $2 }
  $1 == "source" && $2 ~ /^"registry\+/ { print "(" name ", " version ")," }
' "$repo/crates/Cargo.lock")"

rust="$(jq -r --arg locked "$locked" '
  def version_key: split(".") | map(tonumber? // .);

  group_by(.licence)
  | map({
      licence: .[0].licence,
      texts: group_by(.text)
        | map({text: .[0].text, crates: map([.name, .version]) | unique | sort_by(.[0], (.[1] | version_key))})
        | sort_by(.crates[0][0], .text)
    })
  | "// Generated by scripts/licences.bash; do not edit by hand.",
    "",
    "use super::{Group, Text};",
    "",
    "pub(super) const GROUPS: &[Group] = &[",
    (.[] | "Group { licence: \(.licence | tojson), texts: &[",
      (.texts[] | "Text { crates: &[\(.crates | map("\(.[0]) \(.[1])" | tojson) | join(", "))], text: r#\"\(.text)\"# },"),
      "] },"),
    "];",
    "",
    "#[cfg(test)]",
    "pub(super) const LOCKED: &[(&str, &str)] = &[",
    $locked,
    "];"
' <<<"$entries")"

printf '%s\n' "$rust" >"$out"
nix fmt -- "$out"
